# Generated by Django 2.2.11 on 2020-03-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('post_name', models.CharField(blank=True, max_length=300)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('advt_no', models.CharField(blank=True, max_length=100)),
                ('last_date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
