# Generated by Django 2.2.11 on 2020-03-11 05:44

import cms.models.fields
from django.db import migrations
import django.db.models.deletion
import latestnotification.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('latestnotification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='my_placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=latestnotification.models.my_placeholder_slotname, to='cms.Placeholder'),
        ),
    ]
